import "./globals.css";

import type { Metadata } from "next";

import GNB from "@/components/navigation/gnb";
import { ThemeProvider } from "@/components/theme/theme-provider";
import LNB from "@/components/navigation/lnb";
import ClientLayout from "@/components/layout/client-layout";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "hossi-portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("h-screen overflow-hidden antialiased")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="grid h-full grid-rows-[auto,1fr]  grid-cols-[auto,1fr]">
            <LNB className="row-span-2" />

            <GNB className="col-start-2 row-start-1" />

            <ClientLayout className="col-start-2 row-start-2 h-full overflow-auto">
              {children}
            </ClientLayout>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
